// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"gitlab.com/slirx/newproj/internal/graphql/graph/types"
)

type NewPost struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type Post struct {
	ID        int         `json:"id"`
	Text      string      `json:"text"`
	CreatedAt types.Int64 `json:"created_at"`
}

type User struct {
	ID            int    `json:"id"`
	Login         string `json:"login"`
	Name          string `json:"name"`
	PhotoURL      string `json:"photo_url"`
	Followers     int    `json:"followers"`
	Following     int    `json:"following"`
	FollowersList []int  `json:"followers_list"`
	FollowingList []int  `json:"following_list"`
}
